name: lipoenv
channels:
  - anaconda
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - ipykernel
  - pandas
  - matplotlib
  - plotly
  - nbformat
  - scikit-learn
  - pytorch=1.8.1
  - black
  - flake8
  - pip
  - captum=0.3.1
  - pip:
    - albumentations==0.5.2
    - docopt==0.6.2
    - streamlit==0.82.0
    - torch-summary==1.4.5
    - torchvision==0.9.1
    - pytest==6.2.4